### ISSUE TITLE
Clean up repo

### ISSUE THREAD

**Issue by dcwalk** [edgi-govdata-archiving/eis-WARC-archiver#10]
- [x] remove legacy code
- [x] standardize file names
- [ ] update `.gitignore` to exclude logging output

**Comment by sonalranjit** [comment]
ill take care of this

**Comment by sonalranjit** [comment]
Since the docker image outputs to a separate folder there are no outputs from the shell script here to ignore.

**Comment by dcwalk** [comment]
Looks like this was complete-ish and I'll closeout for now :)
