### ISSUE TITLE
addd a test

### ISSUE THREAD

**Issue by titaniumbones** [edgi-govdata-archiving/eis-WARC-archiver#2]
If there were one or two unit tests that can be used to confirm that the script actually works and creates well-formed WARC files that would be great.

**Comment by sonalranjit** [comment]
i have include a test download from the script here https://github.com/guerrilla-archiving/eis-WARC-archiver/tree/master/WARC_OUTPUT/224106 during the event I believe  Jess had tested one of the WARC on a WARC player and it was working. I personally have not tested with a playback, will do when i get some time.

**Comment by dcwalk** [comment]
As we are moving beyond besoke/single-purpose applications, I'm going to close out issues in this repo for now, including this one, as wontdo
