### ISSUE TITLE
Confirm that tool writes well-formed WARC

### ISSUE THREAD

**Issue by titaniumbones** [edgi-govdata-archiving/eis-WARC-archiver#3]
I wasn't sure at the end of hte day whether this had been confirmed. Can someone report on the status, and then I will run a full crawl.

**Comment by jywarren** [comment]
Do you know how this is confirmed? I generated a WARC using `warcprox` in #4, and want to know if that's correctly formatted. 

Looks like `warc-tools` has a validator: https://github.com/kbullaughey/warc-tools

Also some resources here: https://github.com/ukwa/webarchive-discovery

**Comment by sonalranjit** [comment]
I would use [this](https://github.com/ikreymer/webarchiveplayer) tool to confirm WARC files, this tool playsback WARC files.

**Comment by sonalranjit** [comment]
Another tool that can be used to host the playbacks of WARC files written by the same guy who wrote the desktop version is https://github.com/ikreymer/pywb just test ran it on some warc files generate with the docker app. it seems to working

**Comment by dcwalk** [comment]
This turned out to be incredibly hard! But we _did_ wind up with WARCs. 

As we have long since moved beyond besoke/single-purpose applications, I'm going to close out this issue as 'complete enough'
