### ISSUE TITLE
use warcprox to generate standard formed WARC files

### ISSUE THREAD

**Issue by jywarren** [edgi-govdata-archiving/eis-WARC-archiver#4]
OK, looking at this, it seems warcproxy is designed as a separate program which you connect through -- a proxy -- and you then just make all the requests you like, but don't have to store them because warcproxy is doing it for you as it passes the content through. 

Sorry, just to get up to speed. So then the remaining Qs are:

* [ ] how does warcproxy "batch" content that's requested "through" it?
* [ ] how to set up the proxy in a browser
* [ ] how to submit requests without a browser (say via wget)
  * [ ] how to install the warcproxy cert in wget
* [ ] where to install and run warcproxy
* [ ] maybe install warcproxy as a test to try to explore the answers to the above questions by trying it out

A bit more:

certs with wget: https://www.gnu.org/software/wget/manual/html_node/HTTPS-_0028SSL_002fTLS_0029-Options.html
-- could perhaps just use the ‘--no-check-certificate’ flag

https://ide.c9.io/jywarren/warcprox-test - temp VM to test out warcprox

**Comment by jywarren** [comment]
Also: https://github.com/internetarchive/warcprox

**Comment by jywarren** [comment]
wget can be used with `wget -e use_proxy=yes -e http_proxy=127.0.0.1:8000 https://site.com` to go through a local `warcprox` instance

**Comment by jywarren** [comment]
I'm thinking it could be good to set this up on a VM image that can be booted up quickly, preconfigured. Maybe a Dockerfile.

**Comment by jywarren** [comment]
having trouble with some crypto packages on the VM, but it's running locally. Need to look at: http://stackoverflow.com/questions/32518458/importerror-no-module-named-cryptography-hazmat-bindings-openssl#32716740

**Comment by jywarren** [comment]
Super -- full wget command is:

`wget -e use_proxy=on -e https_proxy=127.0.0.1:8000 -e http_proxy=127.0.0.1:8000 -e ftp_proxy=127.0.0.1:8000 --no-check-certificate https://site.com/page`

That generated this WARC: 

https://gist.github.com/jywarren/c3555f5f894a878f1d6f88d2311abb87

How do we tell if it's properly formatted?

**Comment by jywarren** [comment]
I think I could adapt the `wget` calls on this line to go through the proxy, if that's a good next step: https://github.com/edgi-govdata-archiving/eis-WARC-archiver/blob/master/createWarc.py#L34

but we'd want to get it to discard the output since `warcprox` would take care of generating the WARCs.

**Comment by titaniumbones** [comment]
Not sure if Dawn has said this but we're getting access to a small amount of processing power on the big supercomputer network here. Happy to make that available to you if it's convenient -- I have only once or twice set up docker VM's, so if you have the energy to do that I'd be enormously grateful.  


Jeffrey Warren <notifications@github.com> writes:

> I'm thinking it could be good to set this up on a VM image that can be booted up quickly, preconfigured. Maybe a Dockerfile.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.


--

**Comment by dcwalk** [comment]
Hey,

The only two tools I'm aware of for checking warcs in python are:
- IA's `warc` https://github.com/internetarchive/warc (and https://warc.readthedocs.io/en/latest/)
- `warcat` https://github.com/chfoo/warcat/tree/master/warcat

**Comment by dcwalk** [comment]
Using **WARC** (Python 2):
~~~
import warc
f = warc.open("WARCPROX-20170107001055580-00000-6535-localhost-8000.warc")
for record in f:
     print record['WARC-Target-URI'], record['Content-Length']
~~~

`IOError: Bad version line: 'WARC/1.0\n`

Using **warcat** (Python 3):
~~~
python3 -m warcat verify WARCPROX-20170107001055580-00000-6535-localhost-8000.warc 
~~~

`ValueError: Search for pattern exhausted`

**Comment by sonalranjit** [comment]
Hi guys, I think i found a realllyy cool tool that works and archives entire pages, https://github.com/slang800/grab-site#viewing-the-content-in-your-warc-archives 
its a docker app, I just test ran some URLs, all contents are preseved as well. 

For verifying if a created WARC is running, https://github.com/ikreymer/webarchiveplayer this simple archiveplayer will play the WARC file. I test ran it for [this](https://cdxnodengn.epa.gov/cdx-enepa-II/public/action/eis/details?eisId=224106) it was able to fully recover the page and playback works with all the documents and pdfs are preserved.

**Comment by jywarren** [comment]
That sounds great. For `warcprox` in case anyone wants to use that, i did find a pre-made Docker `warcprox` setup:

https://github.com/ukwa/docker-warcprox

**Comment by jywarren** [comment]
OK - do you have a place to run it, and is there any way I can help out with that? How much data do you anticipate downloading?

**Comment by sonalranjit** [comment]
I do not have a place to run this, just by early test runs each EIS page has several PDFs documents so the WARC files are in the range of 10-30 MB, with around 14k + EIS pages, that is more than 420 GB of storage needed. The recommended size for WARCs is to be around 5 GB, I would like to do some more tests and find the best way to do this efficiently and catalogue these WARCs. 

@jywarren  @titaniumbones If I can have access to a small instance Linux box with some significant storage I can start testing and finalize a efficient archiving method to generate and catalogue the entire EIS pages with its documents.

**Comment by dcwalk** [comment]
We are setting up access to a cloud vm for running our tools. An initial scrape was performed with the separate WARCs. But our aim is to rerun once we are properly generating warcs.

@sonalranjit We are are looking to have a single warc. IA has single files much large than that 5GB (e.g. https://archive.org/download/archiveteam_ftpgov_20170101195042). Can you add a link to the recommendations you are seeing to the trello card?
https://trello.com/c/YAzAODMW)

**Comment by sonalranjit** [comment]
@dcwalk those seem to be megawarcs, http://www.archiveteam.org/index.php?title=Dev/Staging 
https://github.com/ArchiveTeam/archiveteam-megawarc-factory

I've update the card on the Trello for the reference to the recommended filesizes for WARCs

**Comment by jywarren** [comment]
So assuming it won't all fit in one WARC, would you want one WARC per dataset, or a 5GB or other cutoff size (which would presumably start a new file once the threshold is passed)?

**Comment by sonalranjit** [comment]
yes @jywarren given that weve had trouble generating a stable WARCs, and finally with grab-site I am starting to see stable WARC files, I would implement it one for each Dataset just to be safe, and then if we are going to upload to IA then we can use the mega warc factory linked above to generate a megawarc

**Comment by jywarren** [comment]
Hi, thanks, just a question -- by "stable" do you mean that it is
identical? I was thinking this could be checked by checksum, but a lot of
timestamps will change, so that probably wouldn't work. How do you assess
stability -- with the tools you linked to on validating warcs? Do they have
a comparison feature?

**Comment by sonalranjit** [comment]
Yes my stable i mean identical to the live site, I believe warcat was mentioned earlier somewhere in this conversation https://github.com/chfoo/warcat this can be ran on a batch of warc files or a megawarc?

**Comment by dcwalk** [comment]
Okay I've reached out to archive.org people and this is the response:

> We write 1GB WARCs normally. We have done "mega-WARCs" in the past, so while its less ideal [the large file size], it probably isn't a huge issue.

It sounds like the workflow you are suggesting @sonalranjit (if I understand correctly) is a good strategy: 
1. use grab-site to generate a warc *per dataset*
2. stage these files 
3. use the megawarc factory to generate a megawarc

I've been told there will need to be validation and am just getting those details. I will post here.

**Comment by librlaurie** [comment]
I'll also chime in to say that we've been talking about bagit for files that aren't designed to be replayed in the way of the warc.

**Comment by titaniumbones** [comment]
@librlaurie  I think you mean this: https://github.com/LibraryOfCongress/bagit-java is that right?

**Comment by dcwalk** [comment]
Hey all, after chatting at Civic Tech tonight, we are gonna work with implementing grab-site at the warc generation method, moved to this issue: #5
