### ISSUE TITLE
use grab-site to generate WARC files

### ISSUE THREAD

**Issue by dcwalk** [edgi-govdata-archiving/eis-WARC-archiver#5]
Picking up from #4 , after testing it looks like [grab-site]()'s cli

> Hi guys, I think i found a realllyy cool tool that crawls and archives entire pages, https://github.com/slang800/grab-site
its a docker app, I just test ran some URLs, all contents are preseved as well.
> For verifying if a created WARC is running, https://github.com/ikreymer/webarchiveplayer this simple archiveplayer will play the WARC file.
> I test ran it for this it was able to fully recover the page and playback works with all the documents and pdfs are preserved.
> guurcwaraz
> I think we should work off this new docker app, it can crawl an entire site so for the EIS pages we can just let the crawler run from https://cdxnodengn.epa.gov/cdx-enepa-II/public/action/eis/search/search which has about 14k pages worth of EIS pages that can be crawled and archived. I would like to test this for a deep crawl, i just ran and crawled a few pages.

**Comment by sonalranjit** [comment]
Currently archiving the EIS docs [page](https://cdxnodengn.epa.gov/cdx-enepa-II/public/action/eis/search/search) using grab-site. Currrently as of this message @ 1806/14633 WARCs generated :/ . The EPA server crashes after running this warcfactory after a lengthy runtime, will monitor today's run and will update this ticket.

**Comment by wdenton** [comment]
Too bad about the crashing, but otherwise good news!

**Comment by dcwalk** [comment]
Can we batch and run in parallel? 

Could get up on existing VM and I could spin up another instance

**Comment by titaniumbones** [comment]
I have an account on cloud east now btw. But I'm so incompetent at this
VM stuff I doubt I'd be able to follow instruction to use it.  Do we
need it? Is there a way for me to give you access?

**Comment by sonalranjit** [comment]
@dcwalk we can try running parallel, never done it on a shell script before. But very willing to try lol, the response time of the EIS docs server is pretty slow.

**Comment by dcwalk** [comment]
We are using grab-site, it worked! 🎉 I'm closing this as fixed :)
