### ISSUE TITLE
Implement and document a grabsite VM which can accept batch requests of URL's

### ISSUE THREAD

**Issue by titaniumbones** [edgi-govdata-archiving/eis-WARC-archiver#6]
If it's possible to set up a grabsite VM in a way that lets us pass batches of requests to it, let's do that right away, and document its use. The next couple of days are crucial.

**Comment by titaniumbones** [comment]
@dcwalk I know you were going to write an issue for this -- I didn't see it so wrote it here -- please edit as you see fit.

**Comment by titaniumbones** [comment]
Also, assigning to everyone because I'm getting scared:  https://insideepa.com/daily-news/trump-transition-preparing-scrub-some-climate-data-epa-website

**Comment by wdenton** [comment]
Yeah, where are we at? Is it just a) making sure the code works and b) running it?

**Comment by titaniumbones** [comment]
As I understand it we're pretty close to that. @dcwalk @sonalranjit how straightforward is it to hook up scraper results to the warcfactory?

**Comment by sonalranjit** [comment]
Update: The docker container [grab-site](https://github.com/edgi-govdata-archiving/grab-site) is running on a machine and harvesting all the EIS 14k URLs scraped from @wdenton ruby [script](https://github.com/edgi-govdata-archiving/epa-eis). I will update the documentation tomorrow morning on how I have setup the docker container and is currently harvesting.

**Comment by sonalranjit** [comment]
think this is done with the most recent updates on #11 @titaniumbones can i close this if you are satisfied.

**Comment by dcwalk** [comment]
Closing a little late (aii!)
