### ISSUE TITLE
Test WARC Archiver application on Windows

### ISSUE THREAD

**Issue by IslandRum88** [edgi-govdata-archiving/eis-WARC-archiver#8]
Bash commands are untested on windows.

**Comment by IslandRum88** [comment]
I was unsuccessful in getting the application to run on Windows 7 and 8.1.  For Windows 10, I don't have a testing environment.  From the research I did, the volume mount is something that has been tested more thoroughly on Windows 10.  

Here are the errors I encountered:
1)  Volume mount on windows 7/8.1 on docker is unreliable.  The mapping between the docker /data/ folder and the windows folder did not work consistently.  It worked successfully when I tried it on C:\Users\Documents for example.com.    However, when I tried it on the other EPA URLs I encountered python errors with the environment variables on the work Archiver . 
2) I tried getting around this by not mapping to a windows folder, running the work Archiver on docker, zipping the files and then copying them to a folder on the host computer.  This didn't work as well. Some of the issues I encountered was that the bash script I wrote wouldn't recognize the generated folder name from warcfactory.  I suspect this was due to the length of the folder.  I also tried renaming the files and then copying them.  The commands worked when I ran them within the container but they did not work when I tried performing a "docker exec" from the host.  

For future purposes here is some of the code that was used:

for line in $lines; do

    #get the date
    #datestr=`date +%Y-%m-%d`

    #remove first 8 characters and convert ? and / to -
    #line_tmp=${line:8}
    #line_tmp=${line_tmp//"?"/"-"}
    #line_tmp=${line_tmp//"/"/"-"}
    #echo "line_tmp: $line_tmp"

    #get the doc id
    docid=$(echo $line| cut -d'=' -f 2)

    zipfile="$docid.tgz"
    echo "zipfile: $zipfile"

    #not sure why warcfactory has two folder formats but accompanying.
    #foldername1=$(echo "$line_tmp--$datestr-$docid")
    #foldername2=$(echo "$line_tmp--$datestr-$docid")

    #echo "foldername: $foldername1"

    docker exec $containerid mv $foldername1 $line_tmp

    #docker exec -t -i $containerid -c 'tar czvf $zipfile $foldername1'
    docker exec $containerid tar czvf $zipfile $line_tmp
    sleep 5

    docker cp $containerid:/data/$zipfile c:/Users/Mark/Documents/warc_data

    ##docker exec $containerid rm -rf /data/*


done

**Comment by dcwalk** [comment]
Thank you for all your help with this @IslandRum88 !

However, as we are moving beyond besoke/single-purpose applications, I'm going to close out issues in this repo for now, including this one, as `wontdo`
