### ISSUE TITLE
Standardize parse-urls.sh to conform to harvesting tools

### ISSUE THREAD

**Issue by dcwalk** [edgi-govdata-archiving/eis-WARC-archiver#9]
See https://github.com/edgi-govdata-archiving/workflow/tree/master/harvesting-toolkit

**Comment by sonalranjit** [comment]
Does this mean you want a UUID for all the warcs generated, just in the format described in the docs? @dcwalk

**Comment by dcwalk** [comment]
I added comments in #11 about what I meant, sorry, I'm confusing when I try to type fast. Do they make sense?

**Comment by sonalranjit** [comment]
marking this as done since the shell script accepts filepath to the URL file
